name: hr_test
description: A hr_test build by using flutter for web.
# version: 1.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  # Enables the `pub run build_runner` command
  build_runner: ^1.6.5

  # Includes the JavaScript compilers
  build_web_compilers: ^2.1.5

  # The Font Awesome Icon pack available as Flutter Icons.
  font_awesome: any

#  font_awesome_flutter: ^8.5.0

# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub
dependency_overrides:


flutter:
  uses-material-design: true
#  assets:
#    - web/assets/